
# root

root:
    path:       /    
    defaults:   { _controller: AppBundle:Default:index }
    
# login

login:
    path:       /login
    defaults:   { _controller: AppBundle:Login:index }

loginDo:
    path:       /login.do
    defaults:   { _controller: AppBundle:Login:loginDo }

loginError:
    path:       /login.error/{errorcode}
    defaults:   { _controller: AppBundle:Login:loginError }

# signup

signup:
    path:       /signup
    defaults:   { _controller: AppBundle:Signup:index }

signupDo:
    path:       /signup.do
    defaults:   { _controller: AppBundle:Signup:signupDo }

signupError:
    path:       /signup.error/{errorcode}
    defaults:   { _controller: AppBundle:Signup:signupError }

# main

main:
    path:       /main
    defaults:   { _controller: AppBundle:Main:index }
    
    
newcomment:
    path:       /newcomment
    defaults:   { _controller: AppBundle:Main:newComment }
    
deletecomment:
    path:       /deletecomment
    defaults:   { _controller: AppBundle:Main:deleteComment }    
    
# aboutus

aboutus:
    path:       /aboutus
    defaults:   { _controller: AppBundle:Main:aboutus }

# logout

logout:
    path:       /logout
    defaults:   { _controller: AppBundle:Login:logout }
