# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:    
    model.user:
        class: AppBundle\Model\UserModel
        arguments: [@doctrine.orm.entity_manager, @service_container]
      
    model.post:
        class: AppBundle\Model\PostModel
        arguments: [@doctrine.orm.entity_manager, @service_container]
        
    model.session:
        class: AppBundle\Model\SessionModel
        arguments: [@doctrine.orm.entity_manager, @service_container]

    model.enterprise:
        class: AppBundle\Model\EnterpriseModel
        arguments: [@doctrine.orm.entity_manager, @service_container]

    model.rol:
        class: AppBundle\Model\RolModel
        arguments: [@doctrine.orm.entity_manager, @service_container]

