AppBundle\Entity\Document:
    type: entity
    repositoryClass: AppBundle\Entity\DocumentRepository
    table: document
    id:
        id:
            type: integer
            nullable: false                        
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        originalName:
            type: string
            nullable: false
            length: 255                        
        name:
            type: string
            length: 255
            nullable: false                            
    manyToOne:
        fk_postId:
            targetEntity: AppBundle\Entity\Post
            joinColumn:
                name: postId
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
