AppBundle\Entity\Enterprise:
    type: entity
    table: enterprise
    id:
        id:
            type: integer
            nullable: false            
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
            nullable: false
        address:
            type: string
            length: 255
            nullable: false                        
        dateIni:
            type: bigint
            nullable: false
            options:
                unsigned: true            
        city:
            type: text
            length: 255
            nullable: false
        postalCode:
            type: integer
            nullable: false
            options:
                unsigned: true            
        description:
            type: text
            nullable: false                        
    lifecycleCallbacks: {  }
