AppBundle\Entity\Post:
    type: entity
    repositoryClass: AppBundle\Entity\PostRepository
    table: post
    id:
        id:
            type: integer
            nullable: false                        
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: bigint
            nullable: false
            options:
                unsigned: true
        titulo:
            type: string
            length: 255
            nullable: false                        
        description:
            type: text
            nullable: false                        
    manyToOne:            
        fk_userId:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: userId
                referencedColumnName: id
                nullable: false
        fk_postId:
            targetEntity: AppBundle\Entity\Post
            joinColumn:
                name: parentId
                referencedColumnName: id
                nullable: true
                options:
                    default: null
    lifecycleCallbacks: {  }
