AppBundle\Entity\Rol:
    type: entity
    table: rol
    id:
        id:
            type: bigint
            nullable: false                        
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        tipo:
            type: string
            length: 255
            nullable: false        
    lifecycleCallbacks: {  }
