AppBundle\Entity\User:
    type: entity
    repositoryClass: AppBundle\Entity\UserRepository
    table: user
    id:
        id:
            type: integer
            nullable: false                        
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        mail:
            type: string
            length: 255
            nullable: false                        
        username:
            type: string
            length: 50
            nullable: false                        
        password:
            type: string
            length: 16
            nullable: false                                
    manyToOne:
        fk_enterpriseId:
            targetEntity: AppBundle\Entity\Enterprise
            joinColumn:
                name: enterpriseId
                referencedColumnName: id
                nullable: false
        fk_rolId:
            targetEntity: AppBundle\Entity\Rol
            joinColumn:
                name: rolId
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
